version: '3.9'
services:
  client:
    build:
      context: ../..
      dockerfile: shared/docker/Dockerfile.client
    ports: ["8100:80"]
    environment:
      - NG_API_URL=http://localhost:3000/api
    depends_on: [ server ]
  server:
    build:
      context: ../..
      dockerfile: shared/docker/Dockerfile.server
    ports: ["3000:3000"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/app
      - JWT_SECRET=change_me
    depends_on: [ mongo ]
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: {}


